- name: Install Cockpit via shell
  hosts: fedora
  become: true

  tasks:
    - name: Update system and remove cockpit
      shell: |
        dnf update -y
        dnf remove -y cockpit
      args:
        executable: /bin/bash
