---

- hosts: ubuntu
  become: true
  tasks:

  - name: "copying files"
    copy:
      src: /home/wil/ansible/files/site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
