---

- hosts: ubuntu
  become: true
  tasks:

  - name: installing random shit
#    tags: qemu-guest-agent, hollywood, apache2, zip, unzip, cockpit
    package:
      name:
        - apache2
        - zsh
        - fzf
        - git
        - zip
        - unzip
      state: latest
