---

- hosts: master,ubuntu
  become: true
  tasks:

  - name: installing random shit
    tags: apache2,zsh,fzf,git,zip,unzip,mosh
    package:
      name:
        - apache2
        - zsh
        - fzf
        - git
        - zip
        - unzip
        - mosh
      state: latest
