---
- name: Update and upgrade packages on Debian-based systems
  hosts: ubuntu,master
  become: yes
  tasks:
    - name: Update package cache
      package:
        update_cache: yes
        cache_valid_time: 3600  # Only update if cache is older than 1 hour

    - name: Upgrade all packages
      package:
        upgrade: dist
