---

- hosts: ubuntu
  become: yes
  tasks:

  - name: "creating users"
    user:
      name: user1
      group: root
      state: absent

  - name: "downloading a remote file and unziping it"
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.12.1/terraform_1.12.1_linux_386.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
